name: ArchonCrates
main: com.HamiStudios.ArchonCrates.Main
version: 10.0
softdepend: [Vault]
commands:
   ArchonCrates:
      description: Main command for ArchonCrates
      usage: /<command>
      aliases: ac